version: "3.8"

services:
  # Serviço da API .NET
  api:
    image: contax_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contax-api-container
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=contaxdb;Username=postgres;Password=seila123"
      Jwt__Key: "dcd595086d344af278425b8c58eebae3"
      ASPNETCORE_ENVIRONMENT: "Development"

    networks:
      - minha_rede_global

  # Serviço do PostgreSQL
  db:
    image: postgres:latest
    container_name: contax-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seila123
      POSTGRES_DB: contaxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - minha_rede_global

# Redes e volumes
networks:
  minha_rede_global:
    external: true

volumes:
  postgres_data:
